### ISSUE TITLE
Get wrong Results

### ISSUE THREAD

**Issue by lixiangyu-1008** [Huangying-Zhan/Depth-VO-Feat#18]
hi
when I use your method for the depth experiment using stereo images pairs. With the train go on , my disparity will go all the dark. Do you know what cause this ?

**Comment by Huangying-Zhan** [comment]
Hi @lixiangyu-1008, thank you for reporting the issue. I am not sure about the reason at the moment without more information. However, here are some suggestions that you can check for the experiment.

(1) To make it clear, in our experiments, we are predicting `inverse depth map` instead of the `disparity map`. 

(2) To ensure a positve prediction (inverse depth), we have a ReLU layer before the final prediction. If you are following the original architecture and the predictions go all the dark, I will guess the prediction somehow becomes all zero because of the ReLU layer. I will suggest checking the prediction at iteration-0 to see if it happens at the beginning. If that's the case, it should be related to the initialization.

(3) However, In the depth experiment with the provided setting, it is supposed not to be all-zero at the beginning. We use the ImageNet model as initialization, please check if you are using the provided model for initialization. 

(4) The provided initialization is supposed to give a positive prediction and the values are small. 

Please let me know if you have more information about the issue.

**Comment by lixiangyu-1008** [comment]
hi @Huangying-Zhan  thank you for replying me in detail. following is my question:
1. Now I am not use the caffe to run your experiment, I use the tensorflow to run your work. Most of the code are git from others work like you.

2.So I want to know the differences between the **disparity map** and **inverse depth map** , I just use the disparity output from the normal encoder and decoder dispnetwork such as Vgg. and then change the disparity to depth as "depth = 1 / disparity", and then use this depth to warp reference image. 

3.At the training beginning , the disparity was not all the dark, when the warp image become more similar 
to the reference image, the disparity map becomes all dark.

4.So maybe the most part such as network are different from yours,but I just do the depth experiment as your method proposed in your paper. 

thank you.

**Comment by Huangying-Zhan** [comment]
Hi @lixiangyu-1008, 
(1) The difference between inverse_depth and disparity
`inverse_depth = 1.0/depth` 
`dispairty = fx*Baseline/depth`, which you can check from most stereo matching tutorial. e.g. https://courses.cs.washington.edu/courses/cse455/09wi/Lects/lect16.pdf slide 10-14

(2) Disparity map becomes dark.
If you are predicting disparity map, to get the depth, you should use `fx*baseline/disparity`. However, I am not sure if this is the reason because if you just use `depth = 1 / disparity` consistently then you are predicting `inverse depth map` instead.
About the statement: __when the warped image become more similar to the reference image, the disparity map becomes all dark__ 
To make it clear, could you define your reference image here?
Is it the image that you want to synthesize or the image that you get the color intensity?
The reason I am asking is because, If the disparity/inverse depth map becomes all dark and `dark=0`, it means the warped image should look exactly same as the source image (where you get color intensity).  

The way I used to debug is to check the image difference between the warped image and the reference image so that to ensure the warping process is correct.

**Comment by lixiangyu-1008** [comment]
Hi @Huangying-Zhan , thanks for reply!

1. The warp formula I used is:
**p(R,t2) = K * Tl->R * DL,t2(pL,t2) K^-1 * pL,t2**  which is  the formula (4) in your paper.
then using  differentiable bilinear interpolation to warp the reference image.

2. the source image I define is  **p(R,t2)**  , the reference image is **pL,t2** .  the Network I used is an encoder-decoder dispNet , the input is the **pL,t2** , get the disparity(**pL,t2**) , and then I tyr  both **depth = fx*baseline/disparity**  and **depth = 1 / disparity**   to warp . but the disparity always go dark .

3.I found the warp image(synthesize image) always looks like to source image .

**Comment by Huangying-Zhan** [comment]
It looks correct to me for the process. I am not sure about the problems you are encountering.
Here are some suggestions that I will try in order to find the bug.

(1) Non-linearity for the prediction
Since you said the prediction goes to all-zero, I would assume you have a non-linearity layer at the end of network. If you have non-linearity (e.g. ReLU) at the last layer for prediction, try to remove the non-linearity layer. This will give some -ve prediction but it shouldn't give all-zero prediction. If this trial gives you reasonable prediction, maybe you can try to play with the initialization.

(2) Check the warping process
Try to use GT depth & GT relative pose to check the warping process. Part of KITTI dataset has denser GT depths, you can convert these depth into disparity/inverse depth and pass GT disparity & pose to your layers/warping operations. If this gives wrong warped image. Then you can double check the warping process.

Hope this help.

**Comment by lixiangyu-1008** [comment]
Hi @Huangying-Zhan:
thanks you very much for replying , I will have a try as you said!

**Comment by lixiangyu-1008** [comment]
hi @Huangying-Zhan :
when I get the out **inverse depth** , then I use it to evaluate the depth . but the results is :

Abs Rel | Sq Rel | RMSE | RMSE log | D1-all | <1.25 | <1.25^2 | <1.25^3
0.9995 | 16.1915 | 20.024 | 7.674 | 100.000 | 0.000 | 0.000 | 0.000

when I check the depth image of the result , I found the result shouldn't be so bad.

**Comment by Huangying-Zhan** [comment]
Hi @lixiangyu-1008, for the evaluation, if you are running stereo training experiment, I believe it is an issue of conversion between your prediction and depth.  Considering that you are running other software and this is not really an issue of the released code. I would suggest discussing the problem via email instead of this issue page.
Could you reach me via my university email (huangying.zhan@adelaide.edu.au)? Thank you.
